### ISSUE TITLE
nonempty_list latex output is incomplete

### ISSUE THREAD

**Issue by zapashcanon** [Lelio-Brun/Obelisk#11]
Hi,

On the same file than the one in #10 ; on the line with the `nonempty_list`, here's what I get in the LaTeX output:

```tex
  & \grambar &\MATCH*{} \expr*{} nonempty\_list \zzzzzzEND*{}\\
```

Which visually gives something like: `MATCH <expr> nonempty_list END`.

Obviously, something is missing, it should be: `MATCH <expr> nonempty_list(<match_case>) END`.

**Comment by Lelio-Brun** [comment]
Yes, it looks like a bug but it comes directly from the fact that `nonempty_list` was not properly recognized. 
The bug here comes from the fact that the symbol `nonempty_list` is not defined in the file (obviously since it comes from the standard library of Menhir), and thus Obelisk treats it as a terminal, ignoring the parameters. 
This case should never happen anyway, so it should be fixed by https://github.com/Lelio-Brun/Obelisk/commit/4951830619311440c54aad2876534d376d3f25a4.

**Comment by zapashcanon** [comment]
Yep, I suspected it was related in some ways... Thanks !
